config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vote.urls')),
]

vote/urls.py
from django.contrib import admin
from django.urls import path, include
from vote import views

app_name = 'vote'

urlpatterns = [
    path('home', views.home, name='home'),
    path('vote', views.home, name='vote'),
    path('result', views.home, name='candidate'),
    path('candidate', views.candidate, name='candidate'),
    path('detail', views.detail, name='detail'),
    path('answer', views.save_answer, name='save_answer'),
    path('api/get/quiz-list', views.get_quiz_list, name='get_quiz_list'),
    path("", views.user_info, name="user_info"),
]

vote/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django import forms


class Candidate(models.Model):
    num = models.PositiveIntegerField(verbose_name="후보자번호")
    name = models.CharField(max_length=100, verbose_name='후보자이름')
    poster = models.ImageField(
        upload_to='profile_image/%Y/%m/%d', verbose_name='프로필 이미지', blank=True)
    url = models.URLField(verbose_name='온라인공약집링크', blank=True)


# def is_nickname(value):
#     if value == None:
#         raise forms.ValidationError("no")


class User(AbstractUser):
    nickname = models.CharField(
        max_length=100, verbose_name="닉네임", blank=True, null=True)
    age = models.PositiveIntegerField(verbose_name='나이', blank=True, null=True)
    job = models.CharField(
        max_length=100, verbose_name='직업', blank=True, null=True)
    result = models.ForeignKey(
        Candidate, on_delete=models.CASCADE, blank=True, null=True)
    TYPE_OF_GENDER = (
        ('male', '남성'),
        ('female', '여성'),
        ('none', '선택하지않음'),
    )
    gender = models.CharField(
        max_length=20, choices=TYPE_OF_GENDER, blank=True, null=True)
    username = models.CharField(
        max_length=150, verbose_name="이름", blank=True, null=True)

    USERNAME_FIELD = "id"
    REQUIRED_FIELDS = ["username", ]

    def __str__(self):
        if self.nickname:
            return self.nickname
        elif self.username:
            return self.username
        elif self.age:
            return str(self.age)

    # def clean(self, *args, ** kwargs):
    #     nickname = self.nickname
    #     if nickname == "":
    #         raise ValidationError("사용자의 닉네임을 입력하세요.")


class Quiz(models.Model):
    num = models.PositiveIntegerField(verbose_name="질문 번호")
    question = models.TextField(verbose_name="질문")
    background = models.TextField(verbose_name="질문에 대한 배경 설명")

    def __str__(self):
        return self.question


class Example(models.Model):
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, related_name="examples", verbose_name="질문")
    num = models.PositiveIntegerField(verbose_name="선택지 번호")
    title = models.TextField(verbose_name="선택지")
    is_answer = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Enrollment(models.Model):
    num = models.PositiveIntegerField(verbose_name="질문 번호")
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="enrollments", verbose_name="유저")
    example = models.ForeignKey(
        Example, on_delete=models.CASCADE, related_name="enrollments", verbose_name="선택한 선택지")

    def __str__(self):
        return str(self.num)

vote/forms.py
from django import forms
from .models import User
# from django.contrib.auth.forms import UserCreationForm


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        # fields = "__all__"
        fields = ["nickname", "age", "job", "result", "gender"]

        # def clean_nickname(self, *args, **kwargs):
        #     nickname = self.cleaned_data.get("nickname")
        #     print(nickname)
        #     if nickname == "hi":
        #         raise forms.ValidationError("닉네임을 입력하세요")
        #     return nickname

vote/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect
from vote.models import *
from .forms import UserForm
from .models import User, Candidate
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from .forms import UserForm
from .models import User, Candidate, Enrollment
from django.views.decorators.csrf import csrf_exempt
import json
from .calculate_util import *
from django.http import JsonResponse


def home(request):
    return render(request, 'vote/home.html')


def get_quiz_list(request):
    quizs = Quiz.objects.prefetch_related('examples').all()

    context = {
        "quiz_list": [{
            "id": q.id,
            "question": q.question,
            "examples": [
                {
                    "title": e.title,
                    "is_answer": e.is_answer
                } for e in q.examples.all()]
        } for q in quizs]
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

# user 정보


def user_info(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            # 추가사항
            if((form.cleaned_data.get("nickname") == None) or (form.cleaned_data.get("age") == None) or (form.cleaned_data.get("job") == None)):
                ctx = {
                    "form": form,
                    "error": "닉네임, 나이, 직업을 입력해주세요."
                }
                return render(request, "vote/user_info.html", ctx)

            user = form.save()
            user.username = user.id
            user.save()

            is_user = authenticate(request, username=user.username)
            if is_user is not None:
                auth_login(request, is_user)

            return render(request, "vote/home.html")
        else:
            ctx = {
                "form": form,
            }
            return render(request, "vote/user_info.html", ctx)
    if request.method == "GET":
        form = UserForm()
        print('폼입니다',form)
        ctx = {
            "form": form,
        }
        return render(request, "vote/user_info.html", ctx)


@csrf_exempt
def save_answer(request):
    req = json.loads(request.body)
    quiz_id = req["quizId"]
    example_id = req["exampleId"]
    example = Example.objects.get(id=example_id)
    enrollment = Enrollment.objects.create(
        num=quiz_id, user=request.user, example=example)
    print(enrollment)
    # todo 현재 로그인 중인 유저의 정보를 가져오기
    # user = User.objects.all()
    return render(request, "vote/user_info.html")


def candidate(request):
    user = User.objects.get(id=request.user.id)
    enrollment = Enrollment.objects.filter(user=user)
    response_list = []
    idx = 0
    for i in enrollment:
        if(idx == 15):
            break
        print('i : ', i)
        response_list.append(i.example.num)
        idx += 1

    print("idx", idx)
    print('user', user)
    print('enrollment', enrollment)
    print('response_list', response_list)

    calculation = calculate(response_list=response_list)
    score_sum = calculation[-1]
    score_percentage = calculation[0]
    if score_sum[0] > score_sum[1]:
        winner = '기호 1번 더불어민주당 박영선'
        win_rate = score_sum[0]
        win_cat = score_percentage[0]
        main_color = '#004EA1'
        sub_color = '#00A0E2'
    else:
        winner = '기호 2번 국민의 힘 오세훈'
        win_rate = score_sum[1]
        win_cat = score_percentage[1]
        main_color = '#E61E2B'
        sub_color = '#F18170'

    # win_list = [win_cat[0], win_cat[1], win_cat[2],
    #             win_cat[3], win_cat[4], win_cat[5]]

    # win_dic = {"win_personal": win_cat[0], "win_real_estate": win_cat[1], "win_economy": win_cat[2],
    #            "win_welfare": win_cat[3], "win_youngs": win_cat[4], "win_social_value": win_cat[5]}

    # return JsonResponse({"user": user.nickname, "winner": winner, "win_rate": round(win_rate*100, 1), "win_dic": win_dic, "win_list": win_list})
    ctx = {
        'user': user,
        'winner': winner,  # 후보자
        'win_rate': round(win_rate*100, 1),  # 예측 종합 일치율
        'win_rate_over': float(round(win_rate*100, 1)+4),  # 예측 종합 일치율
        'win_personal': win_cat[0],
        'win_real_estate': win_cat[1],
        'win_economy': win_cat[2],
        'win_welfare': win_cat[3],
        'win_youngs': win_cat[4],
        'win_social_value': win_cat[5],
        'main_color' :main_color,
        'sub_color' :sub_color,
    }
    return render(request, 'vote/result.html', ctx)


def detail(request):
    user = User.objects.get(id=request.user.id)
    enrollment = Enrollment.objects.all()

    response_list = []
    for i in enrollment:
        response_list.append(i.example)

    calculation = calculate(response_list=response_list)
    score_sum = calculation[-1]
    score_percentage = calculation[0]
    if score_sum[0] > score_sum[1]:
        winner = '기호 1번 박영선'
        answer_list = [[1], [3, 4], [2], [1, 3], [1],
                       [2], [1], [2], [2], [1], [2], [1], [0], [2]]
        win_rate = score_sum[0]
        win_cat = score_percentage[0]
    else:
        winner = '기호 2번 오세훈'
        answer_list = [[2], [1, 2, 3, 4], [1], [1, 2], [2],
                       [1], [3], [1], [1], [2], [1], [2], [2], [1]]
        win_rate = score_sum[1]
        win_cat = score_percentage[1]
    ox = []

    for i in range(2, 14):
        if response_list[i] in answer_list[i]:
            ox.append('o')
        else:
            ox.append('x')
    print(ox)

    ctx = {
        'user': user,
        'winner': winner,  # 후보자
        'win_rate': round(win_rate*100, 1),  # 예측 종합 일치율
        'win_rate_over': int(round(win_rate*100, 1)+5),  # 예측 종합 일치율
        'win_personal': win_cat[0],
        'win_real_estate': win_cat[1],
        'win_economy': win_cat[2],
        'win_welfare': win_cat[3],
        'win_youngs': win_cat[4],
        'win_social_value': win_cat[5],
        'ox3': ox[0],
        'ox4': ox[1],
        'ox5': ox[2],
        'ox6': ox[3],
        'ox7': ox[4],
        'ox8': ox[5],
        'ox9': ox[6],
        'ox10': ox[7],
        'ox11': ox[8],
        'ox12': ox[9],
        'ox13': ox[10],
        'ox14': ox[11],
    }
    return render(request, 'vote/detail.html', ctx)

    # win_dic = {"win_personal": win_cat[0], "win_real_estate": win_cat[1], "win_economy": win_cat[2],
    #            "win_welfare": win_cat[3], "win_youngs": win_cat[4], "win_social_value": win_cat[5]}

    # return JsonResponse({"user": user, "winner": winner, "win_rate": round(win_rate*100, 1), "win_dic": win_dic, "ox_list": ox})

vote/templates/vote/ajax-test.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <style>
            .none {
                display: none;
            }
        </style>
    </head>
    <body>
        hihi
        <div class="num">{{i}}</div>
        <div class="num1 none">now you see this</div>
        <button onclick="onClickPlus()">{%csrf_token%}plus</button>

        <script>
            const request = new XMLHttpRequest();

            const onClickPlus = () => {
                const url = "/test/plus/";
                let numdiv = document.querySelector(".num").innerText;
                console.log(numdiv);
                request.open("POST", url, true);
                request.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                request.send(JSON.stringify({ numdiv }));
            };

            const handleResponse = () => {
                if (request.status <= 400) {
                    const { numjson } = JSON.parse(request.response);
                    const numdiv = document.querySelector(".num");
                    const numdivone = document.querySelector(".num1");
                    const num = numdiv.innerText;
                    const count = Number(num) + 1;
                    numdiv.innerText = count;
                    numdiv.classList.add("none");
                    numdivone.classList.remove("none");
                }
            };

            request.onreadystatechange = () => {
                if (request.readyState === XMLHttpRequest.DONE) {
                    handleResponse();
                }
            };
        </script>
    </body>
</html>

vote/templates/vote/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

        {% block style %} {% endblock %} {% block styleSignup %} {% endblock %} {% block script %} {% endblock %}
        {%block scriptSignup %} {% endblock %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
        <style>
            body div {
                overflow-x: hidden;
            }
        </style>
        <title>Vote47</title>
    </head>
    <body>
        <nav>
            <div class="navbar">
                <a href="{%url 'vote:user_info'%}">
                    <img src="{%static 'media/logo/logogo.png' %}" alt="" height="30vh" />
                </a>
            </div>
        </nav>
        {% block main %} {% endblock %} {% block signup %} {% endblock %}
    </body>
</html>

vote/templates/vote/detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>detail</title>
    </head>
    <body>
        <h3>부동산 공약 {{win_real_estate}}</h3>
        <p>재산세 공약 {{ox3}}</p>
        <p>재건축/재개발 공약 {{ox4}}</p>
        <p>광화문광장 공약 {{ox5}}</p>
        <p>LH사태 관련 {{ox6}}</p>
        <h3>경제 공약 {{win_economy}}</h3>
        <p>재난지원금 공약 {{ox7}}</p>
        <p>출산율 공약 {{ox9}}</p>
        <p>일자리 공약{{ox11}}</p>
        <p>소상공인 공약{{ox12}}</p>
        <h3>복지 공약 {{win_welfare}}</h3>
        <p>재난지원금 공약 {{ox7}}</p>
        <p>성평등 공약 {{ox8}}</p>
        <p>출산율 공약 {{ox9}}</p>
        <p>소상공인 공약{{ox12}}</p>
        <p>장애인 복지 공약{{ox14}}</p>
        <h3>청년 공약 {{win_youngs}}</h3>
        <p>성평등 공약 {{ox8}}</p>
        <p>출산율 공약 {{ox9}}</p>
        <p>교육 공약{{ox10}}</p>
        <p>일자리 공약{{ox11}}</p>
        <p>퀴어축제 공약{{ox13}}</p>
        <h3>사회적 가치 공약 {{win_social_value}}</h3>
        <p>광과문광장 공약 {{ox5}}</p>
        <p>교육 공약{{ox10}}</p>
        <p>퀴어축제 공약{{ox13}}</p>
        <p>장애인 복지 공약{{ox14}}</p>
    </body>
</html>

vote/templates/vote/home.html
{% extends 'vote/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" href="{% static 'css/nav.css' %}" />
<link rel="stylesheet" href="{% static 'css/start-page.css' %}" />
<link rel="stylesheet" href="{% static 'css/quiz-page.css' %}" />
<link rel="stylesheet" href="{% static 'css/result-page.css' %}" />
{% endblock %}

{% block script %}
<script defer src="{% static 'javascript/components/Quiz.js' %}"></script>
<script defer src="{% static 'javascript/components/Result.js' %}"></script>
<script defer src="{% static 'javascript/pages/StartPage.js' %}"></script>
<script defer src="{% static 'javascript/pages/QuizPage.js' %}"></script>
<script defer src="{% static 'javascript/pages/ResultPage.js' %}"></script>
<script defer src="{% static 'javascript/index.js' %}"></script>
{% endblock %}

{% block main %}
<main id="app"></main>
<script>
function getQuizListUrl() {
    return '{% url "vote:get_quiz_list" %}'
}
</script>
{%endblock%}

vote/templates/vote/result.html
{% extends 'vote/base.html' %} {% load static %} {% block styleSignup %}
<link rel="stylesheet" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" href="{% static 'css/nav.css' %}" />
<link rel="stylesheet" href="{% static 'css/sign-up.css' %}" />
{% endblock %} {% block signup %}
<div>
    <div id="login-page">
        <div class="inner-container">
            <p style="margin-top: 10px; margin-bottom: 10px"><b>{{user}}</b>님에게 가장 적합한 후보는</p>
            {%if winner == '기호 2번 국민의 힘 오세훈'%}
            <img
                src="http://info.nec.go.kr/photo_20210407/Gsg1100/Hb100138272/gicho/100138272.JPG"
                alt=""
                width="250px"
            />
            {%else%}
            <img
                src="http://info.nec.go.kr/photo_20210407/Gsg1100/Hb100138295/gicho/100138295.JPG"
                alt=""
                width="250px"
            />
            {%endif%}
            <p><b class="name" style="color:{{main_color}}">{{winner}}</b>입니다.</p>
            <br />
            <div class="total-percentage">
                <p style="margin-bottom: 10px">종합 예상 일치율</p>

                <div
                    class="pie-chart2"
                    style="background: conic-gradient({{main_color}} 0% {{win_rate}}%, {{sub_color}} {{win_rate_over}}% 100%);"
                >
                    <span class="center"><p>{{win_rate}}%</p></span>
                </div>
            </div>
            <div class="graphbox">
                <p style="margin-top: 30px; margin-bottom: 10px; text-align: center">카테고리별 예상 지지도</p>
                <ul class="graph">
                    <li>
                        <div style="background-color: {{sub_color}}">
                            <span style="background-color:{{main_color}}; height:{{win_personal}}%"></span>
                        </div>
                        <p class="final-data">{{win_personal}}%</p>
                        <p class="final-data">
                            후보자 <br />
                            개인
                        </p>
                    </li>
                    <li>
                        <div style="background-color: {{sub_color}}">
                            <span style="background-color:{{main_color}}; height:{{win_real_estate}}%"></span>
                        </div>
                        <p>{{win_real_estate}}%</p>
                        <p>
                            부동산 <br />
                            정책
                        </p>
                    </li>
                    <li>
                        <div style="background-color: {{sub_color}}">
                            <span style="background-color:{{main_color}}; height:{{win_economy}}%"></span>
                        </div>
                        <p>{{win_economy}}%</p>
                        <p>
                            경제 <br />
                            정책
                        </p>
                    </li>
                    <li>
                        <div style="background-color: {{sub_color}}">
                            <span style="background-color:{{main_color}}; height:{{win_welfare}}%"></span>
                        </div>
                        <p>{{win_welfare}}%</p>
                        <p>
                            복지 <br />
                            정책
                        </p>
                    </li>
                    <li>
                        <div style="background-color: {{sub_color}}">
                            <span style="background-color:{{main_color}}; height:{{win_youngs}}%"></span>
                        </div>
                        <p>{{win_youngs}}%</p>
                        <p>
                            청년 <br />
                            정책
                        </p>
                    </li>
                    <li>
                        <div style="background-color: {{sub_color}}">
                            <span style="background-color:{{main_color}}; height:{{win_social_value}}%"></span>
                        </div>
                        <p>{{win_social_value}}%</p>
                        <p>
                            사회적 <br />
                            가치
                        </p>
                    </li>
                </ul>
            </div>
            <div class="seemore">
                <p>
                    <a href="http://policy.nec.go.kr/"
                        ><button style="color:{{main_color}};    border: 2px solid {{sub_color}};">
                            공약 전체 보기
                        </button></a
                    >
                </p>
                <p>
                    <a href="{%url 'vote:user_info'%}"
                        ><button style="color:{{main_color}};    border: 2px solid {{sub_color}};">다시하기</button></a
                    >
                </p>
            </div>
        </div>
    </div>
</div>
<script></script>
{% endblock %}

vote/templates/vote/user_info.html
{% extends 'vote/base.html' %} 
{% load static %} 
{% block styleSignup %}
<link rel="stylesheet" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" href="{% static 'css/nav.css' %}" />
<link rel="stylesheet" href="{% static 'css/sign-up.css' %}" />
{% endblock %} 
{% block signup %}
<div>
    <div id="login-page">
        <div class="inner-container">
            <div class='headers'>
                <br>
                <h1 class="title"><i class="fas fa-vote-yea" style='color:#9956f6'></i>Welcome to Vote47</h1>
                <h3>나와 가장 잘 맞는 서울시장 후보 테스트</h3>
            </div>
            <div class='login-intro' >
                <img src="{%static 'media/logo/urbanbrushnet.png'%}" alt="" width=300px>
                <br>
                <p><i class="fas fa-question"></i>  테스트를 위해 유권자님의 정보를 알려주세요!</p>
                <p><i class="fas fa-question"></i>  지금 입력하는 정보는 결과에 영향을 미치지 않아요.</p>
            </div>
            <div class="login-container">
                <form action="" method="POST" class="container">
                    {% csrf_token %} 
                    {% for field in form %} 
                    {% if field.name != "result" and field.name != "gender" %}
                    <div class="login__form-field">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                    </div>

                    {%endif%}
                    {% endfor %}

                    {% if error %}
                            <div class="error">
                                {{ error }}
                            </div>
                    {% endif %}
            
                    <div class="login__form-actions">
                        <button class="restart-btn" type="submit">테스트하기</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script></script>
{% endblock %}